### ISSUE TITLE
express-ws is a dead project.

### ISSUE THREAD

**Issue by lino-levan** [tigoe/websocket-examples#1]
While looking at the top web results for how to do web sockets with express, yours came up very close to the top.

I noted that you were using express-ws in one of your examples but I would strongly suggest removing it. express-ws is a dead project with over 60 open issues and 10 pull requests that lead to nowhere.

There's even been an overflow vulnerability discovered: [https://github.com/HenningM/express-ws/issues/120](https://github.com/HenningM/express-ws/issues/120).

Adding a warning or deleting it as an example is what I would suggest.

**Comment by tigoe** [comment]
Good to know, thanks. change made.
